include:
  - path: ../keycloak/compose.yml
  - path: ../kafka/compose.yml
  - path: ../mongoDb/compose.yml
  - path: ../postgres/compose.yml
    
services:
  answer:
    container_name: answer
    image: ghcr.io/vibe-check-org/antwort-service:latest
    pull_policy: always
    restart: unless-stopped
    env_file: 
      - ./env/answer.env
      - ./.health.env
    volumes:
      - type: bind
        source: ./env/answer.env
        target: /workspace/.env
        read_only: true
      - type: bind
        source: ./.health.env
        target: /workspace/.health.env
      - type: bind
        source: ../../keys/certificate.crt
        target: /workspace/certificate.crt
        read_only: true
      - type: bind
        source: ../../keys/key.pem
        target: /workspace/key.pem
        read_only: true
      - type: bind
        source: ./logs/answer
        target: /opt/app/log
      - type: bind
        source: ./env/answer.env
        target: /opt/app/dist/config/env
        read_only: true
      - type: bind
        source: ./resources/answer
        target: /opt/app/dist/config/resources
        read_only: true
    ports:
      - target: 3000
        published: 3004
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/health/readiness || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  authentication:
    container_name: authentication
    image: ghcr.io/vibe-check-org/authentication-service:latest
    pull_policy: always
    restart: unless-stopped
    env_file: 
      - ./env/authentication.env
      - ./.health.env
    volumes:
      - type: bind
        source: ./env/authentication.env
        target: /workspace/.env
      - type: bind
        source: ../../keys/certificate.crt
        target: /workspace/certificate.crt
        read_only: true
      - type: bind
        source: ../../keys/key.pem
        target: /workspace/key.pem
        read_only: true
      - type: bind
        source: ./logs/authentication
        target: /opt/app/log
      - type: bind
        source: ./env/authentication.env
        target: /opt/app/dist/config/env
        read_only: true
      - type: bind
        source: ./resources/authentication/
        target: /opt/app/dist/config/resources/
        read_only: true
    ports:
      - target: 3000
        published: 3005
    depends_on:
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/health/readiness || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  gateway:
    container_name: gateway
    image: ghcr.io/vibe-check-org/gateway-service:latest
    pull_policy: always
    restart: unless-stopped
    env_file: 
      - ./env/gateway.env
      - ./.health.env
    volumes:
      - type: bind
        source: ./env/gateway.env
        target: /workspace/.env
        read_only: true
      - type: bind
        source: ./.health.env
        target: /workspace/.health.env
      - type: bind
        source: ../../keys/certificate.crt
        target: /workspace/certificate.crt
        read_only: true
      - type: bind
        source: ../../keys/key.pem
        target: /workspace/key.pem
        read_only: true
      - type: bind
        source: ./logs/gateway
        target: /opt/app/log
      - type: bind
        source: ./resources/gateway
        target: /opt/app/dist/config/resources
        read_only: true
    depends_on:
      authentication:
        condition: service_healthy
      notification:
        condition: service_healthy
      answer:
        condition: service_healthy
      questionnaire:
        condition: service_healthy
      user:
        condition: service_healthy
      vibeProfile:
        condition: service_healthy
    ports:
      - target: 3000
        published: 3000

  notification:
    container_name: notification
    image: ghcr.io/vibe-check-org/notification-service:latest
    pull_policy: always
    restart: unless-stopped
    env_file: 
      - ./env/notification.env
      - ./.health.env
    volumes:
      - type: bind
        source: ./env/notification.env
        target: /workspace/.env
        read_only: true
      - type: bind
        source: ./.health.env
        target: /workspace/.health.env
      - type: bind
        source: ../../keys/certificate.crt
        target: /workspace/certificate.crt
        read_only: true
      - type: bind
        source: ../../keys/key.pem
        target: /workspace/key.pem
        read_only: true
      - type: bind
        source: ./logs/notification
        target: /opt/app/log
      - type: bind
        source: ./env/notification.env
        target: /opt/app/dist/config/env
        read_only: true
      - type: bind
        source: ./resources/notification
        target: /opt/app/dist/config/resources
        read_only: true
    ports:
      - target: 3000
        published: 3006
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/health/liveness || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  questionnaire:
    container_name: questionnaire
    image: ghcr.io/vibe-check-org/questionnaire-service:latest
    pull_policy: always
    restart: unless-stopped
    env_file: 
      - ./env/questionnaire.env
      - ./.health.env
    volumes:
      - type: bind
        source: ./env/questionnaire.env
        target: /workspace/.env
        read_only: true
      - type: bind
        source: ./.health.env
        target: /workspace/.health.env
      - type: bind
        source: ../../keys/certificate.crt
        target: /workspace/certificate.crt
        read_only: true
      - type: bind
        source: ../../keys/key.pem
        target: /workspace/key.pem
        read_only: true
      - type: bind
        source: ./logs/questionnaire
        target: /opt/app/log
      - type: bind
        source: ./env/questionnaire.env
        target: /opt/app/dist/config/env
        read_only: true
      - type: bind
        source: ./resources/questionnaire
        target: /opt/app/dist/config/resources
        read_only: true
    ports:
      - target: 3000
        published: 3003
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/health/readiness || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  user:
    container_name: user
    image: ghcr.io/vibe-check-org/user-service:latest
    pull_policy: always
    restart: unless-stopped
    env_file: 
      - ./env/user.env
      - ./.health.env
    volumes:
      - type: bind
        source: ./env/user.env
        target: /workspace/.env
        read_only: true
      - type: bind
        source: ./.health.env
        target: /workspace/.health.env
      - type: bind
        source: ../../keys/certificate.crt
        target: /workspace/certificate.crt
        read_only: true
      - type: bind
        source: ../../keys/key.pem
        target: /workspace/key.pem
        read_only: true
      - type: bind
        source: ./logs/user
        target: /opt/app/log
      - type: bind
        source: ./env/user.env
        target: /opt/app/dist/config/env
        read_only: true
      - type: bind
        source: ./resources/user
        target: /opt/app/dist/config/resources
        read_only: true
    ports:
      - target: 3000
        published: 3001
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/health/readiness || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  vibeProfile:
    container_name: vibeProfile
    image: ghcr.io/vibe-check-org/vibe-profile-service:latest
    pull_policy: always
    restart: unless-stopped
    env_file: 
      - ./env/vibeProfile.env
      - ./.health.env
    volumes:
      - type: bind
        source: ./env/vibeProfile.env
        target: /workspace/.env
        read_only: true
      - type: bind
        source: ./.health.env
        target: /workspace/.health.env
      - type: bind
        source: ../../keys/certificate.crt
        target: /workspace/certificate.crt
        read_only: true
      - type: bind
        source: ../../keys/key.pem
        target: /workspace/key.pem
        read_only: true
      - type: bind
        source: ./logs/vibe-profile
        target: /opt/app/log
      - type: bind
        source: ./env/vibeProfile.env
        target: /opt/app/dist/config/env
        read_only: true
      - type: bind
        source: ./resources/vibeProfile
        target: /opt/app/dist/config/resources
        read_only: true
    ports:
      - target: 3000
        published: 3002
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/health/readiness || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s





