services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongo
    volumes:
      - type: bind
        source: ../../volumes/mongo/log
        target: /var/log/mongodb
      - type: bind
        source: ../../volumes/mongo/database-data
        target: /data/db
    env_file:
      - .env
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s


  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    env_file:
      - mongo-express.env
    ports:
      - published: 8091
        target: 8081
