CREATE TABLE IF NOT EXISTS antwort (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  fragebogen_id UUID NOT NULL,
  frage_id UUID NOT NULL,
  antwort TEXT NOT NULL,
  erstellt_am TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
