services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s

  kafka:
    depends_on:
      zookeeper:
        condition: service_healthy
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
       KAFKA_ADVERTISED_HOST_NAME: localhost
       #KAFKA_ADVERTISED_HOST_NAME: kafka
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # command: sh -c "export KAFKA_ADVERTISED_HOST_NAME=$(hostname); /usr/bin/start-kafka.sh"