# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 3000

# ==============================================================================
# D a t e n b a n k
# ==============================================================================
db:
  type: postgres

  username: vibe_profile_db_user
  password: VibeCheck10.05.2025
  populate: true

  host: postgres
  schema: vibe_profile_schema
  database: vibe_profile_db

  adminUsername: root
  passwordAdmin: p

# ==============================================================================
# K A F K A
# ==============================================================================
kafka:
  host: kafka
  groupId: VibeCheck-user-service

# ==============================================================================
# K e y c l o a k
# ==============================================================================
keycloak:
  authServerUrl: http://keycloak:8080
  realm: vibeCheck
  clientId: vibeCheck

# ==============================================================================
# L o g g i n g
# ==============================================================================
log:
  level: debug
  #dir: ./log
  pretty: true

# ==============================================================================
# H e a l t h
# ==============================================================================
health:
  prettyPrint: true